spring:
  datasource:
    url: jdbc:mysql://localhost:3306/APPOITMENT_SYSTEM
    username: root
    password: gospodariki
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  logging:
    level:
      org:
        springframework:
          security: DEBUG

  server:
    port: 8080
